---
title: "About"
about:
  template: marquee
  links:
    - icon: github
      href: https://github.com/DanOlner
    - icon: linkedin
      href: https://www.linkedin.com/in/danolner/
    - text: "{{< iconify simple-icons:bluesky >}}"
      href: https://bsky.app/profile/danolner.bsky.social
    - text: "{{< iconify simple-icons:wordpress >}}"
      href: https://www.danolner.net/

---

**Reader, I have missed you. Where have you been?** 

What’s that? Buried under an inconceivably vast and metastasizing word-mountain, you say? Only a shrinking fraction of which is now human-produced, you say? The noise an unbearable tinnitus that makes you want to set your own head in concrete, you say?

**What you need, I think, is another blog.** 

### And look! A subscribe button! Aaah go on. 

(Or the RSS link is top right if you prefer that sort of thing.)

----


<form
  action="
          https://buttondown.com/api/emails/embed-subscribe/danolner
         "
  method="post"
  class="form-label mt-4"
>
  <label for="email">Email ⇉</label>
  <input type="email" name="email" placeholder="" class="form-control" id="exampleInputEmail1"  />
  <input type="hidden" value="1" name="embed" />
  <input type="submit" value="Subscribe" class="btn btn-primary" />
  <p>
    <a href="https://buttondown.com" target="_blank">
      Powered by Buttondown.
    </a>
  </p>
</form>



----

## Contractual "what to expect" section

You'll get a mix of the three following things. 

(I'll indicate in post titles if it's sci-fi/fiction-related, in case you're only here for the spatial economics / other non-fiction ramblings.)[^scifitransport]

1. **Day-job-adjacent writing**, digging a bit deeper into the foundations of the economic / spatial / political ideas connected to my [spatial econ data-sciencing](https://danolner.github.io/) and [other work](https://www.danolner.net/).
2. Mixed in with bonus random topics (my [other writing](https://www.danolner.net/#writing-anchor) is a good guide), there'll be posts asking, **"Are we more than just mindless ants? What systems can we build to maximise our chances of being more than that?" **(Two examples of older posts about this: how humans are [natural distributed systems makers](https://coveredinbees.org.archived.website/3adaptivelandscapes.html), what Balinese rice pest management, Peruvian potato growing and the market economy have in common, why it’s all tangled up with magic and why it means Hayek was wrong; [picking apart](https://www.danolner.net/2022/08/jordan-petersons-zombie-climate-ideas) Jordan Peterson's tediously shallow neoliberalism that underpins his climate nonsense, as a reminder that we are not, in fact, just mindless ants).
3. **I wrote a sci-fi book about AI**, which I finished in the summer of 2022 after four years of research/writing... a couple of months before the 1st chatGPT public release. I'm going to do one more re-draft before [self-publishing](https://www.reddit.com/r/selfpublish/) (after failed attempts to foist it on real publishers[^pub]). I'll write about this process, as well as the book's ideas and themes in an "LLM before / after" light. What still works, what doesn't? Is there any point when every other social media post and news story is now about AI? It's a terrible idea to retrofit too heavily based on new info, but a few tweaks might be fun.



----

## Other websites / contacts

Click through here or see the bottom of this page / top header for [github](https://github.com/DanOlner), [linkedin](https://www.linkedin.com/in/danolner/), [bluesky](https://bsky.app/profile/danolner.bsky.social) and [danolner.net](https://www.danolner.net/) (online CV / projects type page).

Other places of interest might be [Dan's data dispatch](https://danolner.github.io/) for more techie bits (look, same Quarto template!) and the [open econ tools](https://danolner.github.io/RegionalEconomicTools/) website.

Get in touch via LinkedIn or github or danolner at gmail dot com.

----

## About me / this site

I called my first ever blog 'coveredinbees' back in 2006 before embarking on a PhD. The name was an [Izzard-flavoured](https://www.youtube.com/watch?v=CYuvLSFFalo) hat-tip to the [emergence / self-organisation ideas](https://coveredinbees.org.archived.website/node/391.html) I planned to study. (Someone later pointed out I could also have linked to the [Fable of the Bees](https://en.wikipedia.org/wiki/The_Fable_of_the_Bees), didn't think of that at the time.)

Early posts (a few surviving on the wayback machine) like [this](queenyandthetanners2006.html) were largely unstructured rambles of faintly connected thoughts. Various incarnations survived over the years; [this archive](https://coveredinbees.org.archived.website/) was the last one and [this page](https://www.danolner.net/#writing-anchor) lists my favourite bits.

Twenty years later, of course, through diligent practice and academic training, my writing is now like a scalpel. 

Hahahaha. I jest. No. I did manage to [write a PhD](https://github.com/DanOlner/PhD-thesis-n-code) (in twice the time I was supposed to) and a sci-fi book (more on that soon). But from those early puppyish, over-enthusiastic ramblings of youth, I have passed through trying to be something I'm not, back in my autumn years[^1] to "Aaaaa just get on with the rambling. Who cares? We'll all be dead soon."

Slightly less flippantly... coveredinbees (and early C21st blogging generally, a world that still survives at the margins) allowed a kind of free exploration and experimentation that I miss. That dovetails with the direction work is taking, as I'm playing with [opening up economic tools and ideas](https://danolner.github.io/RegionalEconomicTools/). That site leans heavily towards the narrow how-to stuff - I want to open that up, connect to the "so what" and arguments around things like how we measure, how we connect ideas and values through to our tools. 

Setting this up to work through [Quarto](https://quarto.org/) and [github](https://github.com/DanOlner/coveredinbees) is considerably more faff than, say, signing up for Substack. But this gives me **more control and ownership** as well as **leaving an accountability trail** - everything here is on my own machine as well as [stored on github](https://github.com/DanOlner/coveredinbees) (admittedly, owned by Microsoft). If anyone so desires - why would you, that'd be mad, but if you *wanted* to - you could look at the history of any file ([here's](https://github.com/DanOlner/coveredinbees/commits/master/posts/why_sfd/index.qmd) this one's) and see what's changed (e.g. a [recent commit difference](https://github.com/DanOlner/coveredinbees/commit/78788d0ca8ecbc5e46305a3849a196bf17e16165#diff-b4ac3c529b00f3e9f57376c3dd67f1700d6c2c70e2f62874c67ae7307faf0dae)). You could even sign up to github and [add comments](https://github.com/DanOlner/coveredinbees/issues/new?permalink=https%3A%2F%2Fgithub.com%2FDanOlner%2Fcoveredinbees%2Fblob%2F4426c86ade5bd504d01a72e2ab3df02becc26a5d%2Fposts%2Fwhy_sfd%2Findex.qmd%23L1).

In our bold new LLM world, this is also one way to show it's this particular dumb, stumbling [meatsack](https://www.youtube.com/watch?v=T6JFTmQCFHg) awkwardly flapping the words out.

And why make things simple when they can be complicated? The [Douglas Adams principle of programming](https://www.reddit.com/r/quotes/comments/btuvib/i_am_rarely_happier_than_when_spending_an_entire):

> "I am rarely happier than when spending an entire day programming my computer to perform automatically a task that would otherwise take me a good ten seconds to do by hand."


[^1]: I'm not *that* old. I am *quite* old.
[^pub]: I wrote a [little guide](https://www.danolner.net/2023/01/list-of-uk-sci-fi-friendly-literary-agents) to pitching that includes a list of sci-fi friendly agents I collated and some tips/pointers. Chances of success are slim but it's worth the attempt just for how much the process will improve your writing.
[^scifitransport]: "But I was looking for a spatial economics / sci-fi crossover," you say? Sorry, I don't have one of those (yet) but the intriguing [Appliance ](https://www.penguin.co.uk/books/447226/appliance-by-morgan-j-o/9781529115949) by J.O. Morgan has you covered.