---
title: "Buttondown sub test: here's the title!"
author: "Dan Olner"
date: "2025-08-20"
categories: [final]
---

There’s some amazing work being done on how data can be used to support this, and gnarly issues around how evidence gets built into the machinery of governance. Work on inclusive economies has shown (LGA report) there’s no clear connection between raw GVA growth and disposable income growth. Others in, for example, the [SIPHER project](https://sipher.ac.uk/reports/) and Manchester’s inclusive growth analysis unit are asking exactly what role data and evidence can play in attacking spatial inequality(see this great spreadsheet put together by SIPHER that gathers several organisation’s inclusive economy measures into one place). This includes work with communities to create indicators that make sense to them, rather than simply imposing ones institutions prefer to work with (though there is of course still a need to use existing, robust national data sources).

Continuing the inclusive economies theme, there’s a recognition of the deep connection between all the economic and spatial determinants of health written into South Yorkshire’s Integrated Care Partnership health strategy, including the role of housing, employment and access to transport. That’s supported by a mature national data system – fingertips – that is not as well known as it should be, maybe due to its health focus. Because it covers “wider determinants”, it actually contains a huge swathe of the all the best social and economic data, with excellent APIs and R/Python packages, and is the foundation for this epic piece of analysis (word doc download) that supports South Yorkshire’s health strategy.