---
title: "21st Century peer review"
date: "2025-08-19"
categories: [draft]
---

21st century peer review, how to make it work. Separate out all the different types e.g. tiny incremental technical progress in papers (some patenting to get IP) is a very different world to e.g. open urban work. Structures vastly different. Or exploratory thought pieces vs medical testing. Put in context of what we do not want to happen: what happened with supposed ‘citizen science’ for climate change, which was just idiots shouting “I am Galileo!” Some but not all of those oil-funded, some but not all of those with raging Dunning-Kruger. (Cf. [constructive stupidity](https://web.stanford.edu/~fukamit/schwartz-2008.pdf).) 

Other random points:

* Now equivalent of DDOS attack via LLMs...?
* New tools? Github as way to produce, review, edit in a fully open and traceable way?
* The ostensible goal: continue to increase real knowledge a slice at a time. But what role does or could knowledge systems play in this? Back to the original "how does science / how does knowledge growth *actually* work vs how we imagine it should". Overlaps with the [demarcation problem](https://en.wikipedia.org/wiki/Demarcation_problem) / shows up in arguments around [scientism](https://en.wikipedia.org/wiki/Scientism). (That's a really great wikipedia article on the subject).

