---
title: "Draft v final plus bonus TLDR"
author: "Dan Olner"
date: "2025-08-18"
categories: [draft]
---

**Welcome to coveredinbees, a site where I waffle, mull, connect and maybe over time try to hone thoughts into something more digestible.** 

You've got the option of subscribing to [first drafts](https://danolner.github.io/coveredinbees/index.xml) here, as well as [final drafts](https://danolner.github.io/coveredinbees/index-final.xml) (RSS links). 

**The email subscription option defaults to final pieces only - tick the '1st draft' box you want in on the 1st drafts.** 

**Why on Earth would I be giving you the option to read 1st drafts? Isn't life short enough already?** Brief answer followed by longer ramble.

* I'm using "1st draft" here to mean: the start of an idea or topic, in a post that I'll continue to edit, ramble in, add links and connected thoughts, keeping it all in one place and regularly [pushing to github](https://github.com/DanOlner/coveredinbees).
* *In "1st drafts" I'll try and lay out what I think the questions are and get some first points down. These may just be snippets that never go anywhere or they may grow. Though it absolutely will include [shitty first drafts](https://wrd.as.uky.edu/sites/default/files/1-Shitty%20First%20Drafts.pdf) along the way, the point is to get stuff out there, experiment with it and let it grow.
* This is also part of having **more control and ownership** as well as using a structure that **leaves an accountability trail** by being as open as possible. Everything here is on my own machine as well as [stored on Github](https://github.com/DanOlner/coveredinbees) (admittedly, owned by Microsoft). If anyone so desires - why would you, that'd be mad, but if you *wanted* to- you could look at the history of any file ([here's](https://github.com/DanOlner/coveredinbees/commits/master/posts/why_sfd/index.qmd) this one's) and see what's changed (e.g. a [recent commit difference](https://github.com/DanOlner/coveredinbees/commit/78788d0ca8ecbc5e46305a3849a196bf17e16165#diff-b4ac3c529b00f3e9f57376c3dd67f1700d6c2c70e2f62874c67ae7307faf0dae)). You could even sign up to github and [add comments](https://github.com/DanOlner/coveredinbees/issues/new?permalink=https%3A%2F%2Fgithub.com%2FDanOlner%2Fcoveredinbees%2Fblob%2F4426c86ade5bd504d01a72e2ab3df02becc26a5d%2Fposts%2Fwhy_sfd%2Findex.qmd%23L1).[^2]

Also - why write when you can instead spend far too long setting up complex writing systems? What kind of fool just *writes*?

OK, the longer version. 

Words have been getting a bit of a kicking lately. Looming in everyone's vision right now is (as a few people have put it e.g. [here](https://www.spglobal.com/en/research-insights/special-reports/language-modeling-the-fundamentals), [here](https://pmc.ncbi.nlm.nih.gov/articles/PMC11137430/), [here](https://bigwildmindmachine.substack.com/p/the-ny-times-vs-openai)) that humans just lost their monopoly on written language to robots that digested everything ever written, [Johnny-5 style](https://youtu.be/WnTKllDbu5o?t=42) (OK, not like that).

But while everyone argues about just how radical the LLM shift is, the machinery of language has been altering for a good while longer as  [informatics](https://en.wikipedia.org/wiki/Informatics_(disambiguation)) has worked its way into every cell over the last few decades[^informatics].

It's obvious to state, but words are the sinews of social and scientific progress. Informatics is upending much of its old ways of growing, and it's opened us up to language equivalents of distributed [denial of service attacks](https://en.wikipedia.org/wiki/Denial-of-service_attack) - nothing more sophisticated, really, than a bunch of people constantly shouting nonsense while others are in the room trying to think. But it's been effective nonetheless ([climate example](https://www.nature.com/articles/s41598-024-74032-0) in Nature), and LLMs may be pouring petrol on that (see e.g. openAI [here](https://openai.com/index/disrupting-a-covert-iranian-influence-operation/), [here](https://cdn.openai.com/threat-intelligence-reports/influence-and-cyber-operations-an-update_October-2024.pdf), also [here](https://www.wired.com/story/pro-russia-disinformation-campaign-free-ai-tools/)). 

Science (and all other knowledge flavours that accrete around universities) is a still-surviving modernist structure built up layer by layer through argument and counter-argument[^1], a somehow-functioning mix of reason and chance. Science is struggling. Again, it's a mix of the fundamentals - how knowledge production is adapting to new tech, or through inertia failing to, and all the ways language DDOS is affecting it (climate science under attack; 'sick of experts'; in the U.S., direct authoritarian attacks).

It's unavoidably political, of course. Authoritarians want to be the sole source of truth, and twist words accordingly. The internet age suits them just fine. But there's a lot of weird Venn diagram overlap with its apparent opposite, libertarian truthiness. See Peter [Thiel talking about](https://archive.ph/PvS6B#selection-1971.190-1971.446) Eric Weinstein's [term](https://theportal.wiki/wiki/The_Distributed_Idea_Suppression_Complex_(The_DISC)), the 'Distributed Idea Suppression Complex'. As Thiel puts it, 'the internet has already begun our liberation from the DISC prison... the media organisations, bureaucracies, universities and government-funded NGOs that traditionally delimited public conversation".

Gramscian cultural hegemony comparisons [abound](https://www.reddit.com/r/ThePortal/comments/laigmm/bourdieu_and_the_disc_erics_neologisms/), so that's nothing new - and I'm not dismissing the notion that institutions use words to shape reality. What's striking is its banality. You can see the same in [Musk's take on Twitter/X](https://www.businessinsider.com/elon-musk-twitter-fail-collective-superintelligence-2022-11):

> "Because it consists of billions of bidirectional interactions per day, Twitter can be thought of as a collective, cybernetic, super-intelligence."

It's that sufficient-condition "because of" that gets me. Nope, it's not intelligent because of those interactions. My cup of tea consists of *trillions* of bidirectional interactions. It has no smarts. This is exactly the same wilful error that Hayekian thinking is often guilty of (more-so than Hayek himself I think) - if you tear things down, some kind of fairy dust will 'emerge' to replace it. And if you get in the way of that happening, you're part of the DISC / [woke mind virus](https://x.com/search?f=top&q=woke%20mind%20virus%20(from%3Aelonmusk)&src=typed_query).

Intriguing that the outcome ends up following the grain of authoritarianism - that can be seen in the targets that both attack. Both have implicit theories of truth that seem so opposite: one sole, all-controlling source versus an emergent, everywhere-truth that no-one controls. But the effect on the machinery of knowledge generation is more or less identical. Compare to the famous Arendt quote from [Truth and Politics](https://idanlandau.com/wp-content/uploads/2014/12/arendt-truth-and-politics.pdf):  

> "The result of a consistent and total substitution of lies for factual truth is not that the lie will now be accepted as truth and truth be defamed as lies, but that the sense by which we take our bearings in the real world - and the category of truth versus falsehood is among the mental means to this end - is being destroyed."

Let's not push the parallel too far. Libertarians aren't into disappearing people off the street for what they say. But that's why the childishness of DISC thinking is so frustrating - it seems content to enable its opposite.

So that's the world that LLMs have entered, that we find ourselves in now. The (actually very useful) idea of emergence is weaponised by right wing idiots, paving the way for authoritarians to tediously re-prove Arendt over and over, with added trollfarms. To the extent that DISC thinking has a point - knowledge structures *are* dominated by white males on computers like me - they let the *actual* point go sailing past: addressing this means exactly the kind of 'how to diversify voices effectively' thinking most of them seem to loath.

So yes. Another blog will help, I think.

OK, try again. What I like about github, and openly writing there, is all those things I mentioned above - openness, visibility, accountability, ownership. (Shhh about Microsoft, shhhh.) But in these systems, one can also see ways to make knowledge in a distributed way, in a place where there's enough of a level of control to balance collaboration and safety.

It's possible. Places *already exist* where this has worked. Wikipedia is straight-up brilliant (entirely unsurprising people like Musk should [attack it](muskpedia.png)), well-designed tech channelling collaboration into incremental improvements while keeping the idiots at bay.












 

[^informatics]: Strictly, informatics is "the *branch of study* that deals with the structure, properties, and communication of information and with means of storing or processing information" ([OED def](oed_informatics.png))    so it's wrong, but short. All other options are horrible e.g. [information ecosystem](https://mitpress.mit.edu/9780262640428/information-ecologies/) was about the best I could find, not great. Anything better?
[^1]: A Bauman point, that one: modernism - "a ‘total’ order to be erected floor by floor in a protracted, consistent, purpose-guided effort of labour.” (Liquid modernity) 
[^2]: Not quite as ridiculous as it sounds - github is one of the few collab platforms I've found that works across both universities and UK public bodies, where often many websites are blocked (I presume because it's Microsoft owned).







